name: test_airfield
description: "Space for Flutter practice"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  freezed: ^2.4.7
  dio: ^5.4.0
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  json_serializable: ^6.7.1
  go_router: ^13.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9
  build_runner: ^2.4.8
  custom_lint: ^0.6.0

flutter:
  uses-material-design: true
